import React, { useState, useEffect } from 'react';
import { assessmentService, courseService } from '../../services/api';
import { IconClipboard, IconPlus, IconBrain, IconCheckCircle, IconEye, IconLayers, IconBookOpen } from '../../components/common/Icons';

export const ProviderAssessments = () => {
  const [assessments, setAssessments] = useState([]);
  const [courses, setCourses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [selectedAssessment, setSelectedAssessment] = useState(null);
  const [generating, setGenerating] = useState(false);

  // Generation Form State
  const [formData, setFormData] = useState({
    courseId: '',
    difficulty: 'MIXED',
    questionsPerSkill: 5,
    timeLimitMinutes: 30,
    maxAttempts: 2,
  });

  useEffect(() => {
    fetchAssessments();
    fetchCourses();
  }, []);

  const fetchAssessments = async () => {
    try {
      setLoading(true);
      const res = await assessmentService.getAll();
      setAssessments(res.data?.data || []);
    } catch (err) {
      console.error('Failed to load assessments:', err);
    } finally {
      setLoading(false);
    }
  };

  const fetchCourses = async () => {
    try {
      const res = await courseService.getAll();
      setCourses(res.data?.data || []);
    } catch (err) {
      console.error('Failed to load courses:', err);
    }
  };

  const handleGenerateAssessment = async (e) => {
    e.preventDefault();
    if (!formData.courseId) return;

    try {
      setGenerating(true);
      const res = await assessmentService.generate({
        ...formData,
        questionsPerSkill: Number(formData.questionsPerSkill),
        timeLimitMinutes: formData.timeLimitMinutes ? Number(formData.timeLimitMinutes) : null,
        maxAttempts: Number(formData.maxAttempts),
      });

      setShowGenerateModal(false);
      fetchAssessments();
      alert('Assessment successfully generated by Grok AI in DRAFT state! You can now review and publish it.');
    } catch (err) {
      alert(err.message || 'Failed to generate AI assessment.');
    } finally {
      setGenerating(false);
    }
  };

  const handlePublishAssessment = async (id) => {
    if (!window.confirm('Are you sure you want to publish this assessment? Once published, enrolled trainees will be able to take it.')) return;
    try {
      await assessmentService.publish(id);
      fetchAssessments();
      if (selectedAssessment?._id === id) {
        setSelectedAssessment({ ...selectedAssessment, status: 'PUBLISHED' });
      }
      alert('Assessment published successfully!');
    } catch (err) {
      alert(err.message || 'Failed to publish assessment.');
    }
  };

  const handleViewAssessment = async (id) => {
    try {
      const res = await assessmentService.getById(id);
      setSelectedAssessment(res.data?.data || null);
    } catch (err) {
      console.error('Failed to load assessment details:', err);
    }
  };

  const selectedCourse = courses.find((c) => c._id === formData.courseId);

  return (
    <div className="page-container">
      <div className="page-header" style={{ marginBottom: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 className="page-title" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <IconClipboard size={26} color="#3b82f6" /> Course Skill Assessments
          </h1>
          <p className="page-subtitle">
            Generate AI-powered MCQ assessments for course skills, review questions, and publish for enrolled cohorts
          </p>
        </div>
        <button className="btn btn-primary" onClick={() => setShowGenerateModal(true)}>
          <IconBrain size={18} /> Generate AI Assessment
        </button>
      </div>

      {/* Assessment Table */}
      {loading ? (
        <div className="card" style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-muted)' }}>
          Loading assessments...
        </div>
      ) : assessments.length === 0 ? (
        <div className="card" style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-muted)' }}>
          No assessments created yet. Click "Generate AI Assessment" to generate a skill assessment via Grok AI.
        </div>
      ) : (
        <div className="table-responsive card">
          <table className="table">
            <thead>
              <tr>
                <th>Assessment Title</th>
                <th>Course</th>
                <th>Version</th>
                <th>Questions</th>
                <th>Difficulty</th>
                <th>Time Limit</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {assessments.map((a) => (
                <tr key={a._id}>
                  <td>
                    <div style={{ fontWeight: '700', color: 'var(--text-primary)' }}>{a.title}</div>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                      {a.skills?.map((s) => (typeof s === 'string' ? s : s?.skillName || s?.name || 'Skill')).join(', ')}
                    </div>
                  </td>
                  <td>
                    <span className="badge badge-info">{a.courseId?.courseName || 'Course'}</span>
                  </td>
                  <td>v{a.version}</td>
                  <td><strong>{a.totalQuestions || a.questions?.length || 0}</strong></td>
                  <td>{a.difficulty}</td>
                  <td>{a.timeLimitMinutes ? `${a.timeLimitMinutes} mins` : 'Untimed'}</td>
                  <td>
                    <span className={`badge ${a.status === 'PUBLISHED' ? 'badge-success' : a.status === 'DRAFT' ? 'badge-warning' : 'badge-secondary'}`}>
                      {a.status}
                    </span>
                  </td>
                  <td>
                    <div style={{ display: 'flex', gap: '6px' }}>
                      <button className="btn btn-secondary btn-sm" onClick={() => handleViewAssessment(a._id)}>
                        <IconEye size={14} /> Review
                      </button>
                      {a.status === 'DRAFT' && (
                        <button className="btn btn-primary btn-sm" onClick={() => handlePublishAssessment(a._id)}>
                          <IconCheckCircle size={14} /> Publish
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Generate AI Assessment Modal */}
      {showGenerateModal && (
        <div className="modal-backdrop" onClick={() => setShowGenerateModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()} style={{ maxWidth: '600px' }}>
            <div className="modal-header">
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <IconBrain size={22} color="#a78bfa" />
                <h3 style={{ margin: 0 }}>Generate AI Skill Assessment</h3>
              </div>
              <button className="btn-close" onClick={() => setShowGenerateModal(false)}>×</button>
            </div>

            <form onSubmit={handleGenerateAssessment}>
              <div className="modal-body">
                <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '1.25rem' }}>
                  Grok will generate multiple-choice questions mapped strictly to your course curriculum skills, complete with 4 options and answer keys.
                </p>

                <div className="form-group" style={{ marginBottom: '1rem' }}>
                  <label className="form-label">Select Course *</label>
                  <select
                    className="form-control"
                    required
                    value={formData.courseId}
                    onChange={(e) => setFormData({ ...formData, courseId: e.target.value })}
                  >
                    <option value="">Select course...</option>
                    {courses.map((c) => (
                      <option key={c._id} value={c._id}>
                        {c.courseName} ({c.skills?.length || 0} skills defined)
                      </option>
                    ))}
                  </select>
                </div>

                {selectedCourse && (
                  <div style={{ padding: '0.75rem', backgroundColor: 'rgba(59, 130, 246, 0.08)', borderRadius: '6px', marginBottom: '1rem', border: '1px solid rgba(59, 130, 246, 0.2)' }}>
                    <div style={{ fontSize: '0.75rem', color: '#93c5fd', fontWeight: '700', textTransform: 'uppercase', marginBottom: '4px' }}>
                      Skills to be assessed ({selectedCourse.skills?.length || 0}):
                    </div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px' }}>
                      {selectedCourse.skills && selectedCourse.skills.length > 0 ? (
                        selectedCourse.skills.map((s, idx) => (
                          <span key={idx} style={{ fontSize: '0.8rem', backgroundColor: 'rgba(255, 255, 255, 0.05)', padding: '2px 8px', borderRadius: '4px' }}>
                            {typeof s === 'string' ? s : s?.skillName || s?.name || 'Skill'} (Weight: {s?.weight || 'Equal'}%)
                          </span>
                        ))
                      ) : (
                        <span style={{ color: '#f87171', fontSize: '0.8rem' }}>
                          Warning: This course has no skills defined. Please edit the course to add skills before generating assessments.
                        </span>
                      )}
                    </div>
                  </div>
                )}

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
                  <div className="form-group">
                    <label className="form-label">Questions Per Skill</label>
                    <input
                      type="number"
                      className="form-control"
                      min="3"
                      max="10"
                      value={formData.questionsPerSkill}
                      onChange={(e) => setFormData({ ...formData, questionsPerSkill: e.target.value })}
                    />
                    <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Total: {(selectedCourse?.skills?.length || 1) * formData.questionsPerSkill} questions</span>
                  </div>

                  <div className="form-group">
                    <label className="form-label">Difficulty Level</label>
                    <select
                      className="form-control"
                      value={formData.difficulty}
                      onChange={(e) => setFormData({ ...formData, difficulty: e.target.value })}
                    >
                      <option value="MIXED">Mixed (Balanced)</option>
                      <option value="BEGINNER">Beginner</option>
                      <option value="INTERMEDIATE">Intermediate</option>
                      <option value="ADVANCED">Advanced</option>
                    </select>
                  </div>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
                  <div className="form-group">
                    <label className="form-label">Time Limit (Minutes)</label>
                    <input
                      type="number"
                      className="form-control"
                      placeholder="e.g. 30 (blank = untimed)"
                      value={formData.timeLimitMinutes}
                      onChange={(e) => setFormData({ ...formData, timeLimitMinutes: e.target.value })}
                    />
                  </div>

                  <div className="form-group">
                    <label className="form-label">Max Attempts per Trainee</label>
                    <input
                      type="number"
                      className="form-control"
                      min="1"
                      max="5"
                      value={formData.maxAttempts}
                      onChange={(e) => setFormData({ ...formData, maxAttempts: e.target.value })}
                    />
                  </div>
                </div>
              </div>

              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setShowGenerateModal(false)}>Cancel</button>
                <button
                  type="submit"
                  className="btn btn-primary"
                  disabled={generating || !formData.courseId || !selectedCourse?.skills?.length}
                >
                  {generating ? 'Grok AI Generating Questions...' : 'Generate Assessment with Grok'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Review Assessment Modal */}
      {selectedAssessment && (
        <div className="modal-backdrop" onClick={() => setSelectedAssessment(null)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()} style={{ maxWidth: '800px', maxHeight: '85vh', overflowY: 'auto' }}>
            <div className="modal-header">
              <div>
                <h3 style={{ margin: 0 }}>{selectedAssessment.title}</h3>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                  Status: <strong>{selectedAssessment.status}</strong> | Total Questions: <strong>{selectedAssessment.questions?.length}</strong>
                </span>
              </div>
              <button className="btn-close" onClick={() => setSelectedAssessment(null)}>×</button>
            </div>

            <div className="modal-body">
              {selectedAssessment.status === 'DRAFT' && (
                <div style={{ padding: '0.85rem', backgroundColor: 'rgba(245, 158, 11, 0.1)', border: '1px solid #f59e0b', borderRadius: '6px', marginBottom: '1.25rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ fontSize: '0.85rem', color: '#f59e0b' }}>
                    This assessment is in <strong>DRAFT</strong>. Trainees cannot see or take it until you publish.
                  </span>
                  <button className="btn btn-primary btn-sm" onClick={() => handlePublishAssessment(selectedAssessment._id)}>
                    Publish Assessment
                  </button>
                </div>
              )}

              {/* Architecture Explanation Banner */}
              <div style={{ padding: '0.85rem', backgroundColor: 'rgba(59, 130, 246, 0.08)', border: '1px solid rgba(59, 130, 246, 0.25)', borderRadius: '6px', marginBottom: '1.25rem', fontSize: '0.85rem', lineHeight: '1.5' }}>
                <div style={{ fontWeight: '700', color: '#60a5fa', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <IconBrain size={16} /> Two-Phase Adaptive Assessment Structure
                </div>
                <div style={{ color: 'var(--text-secondary)' }}>
                  <strong>Phase 1 (Fixed):</strong> Predefined Case Study Scenario + {selectedAssessment.caseStudyQuestions?.length || selectedAssessment.questions?.length || 0} Fixed MCQs shown below. Fixed upon publishing.
                  <br />
                  <strong>Phase 2 (Dynamic Adaptive):</strong> Subsequent questions are generated on the fly per trainee based on their accumulated evidence. No predefined adaptive questions exist.
                </div>
              </div>

              {/* Case Study Scenario Section */}
              {selectedAssessment.caseStudy?.scenario && (
                <div style={{ padding: '1.25rem', backgroundColor: 'rgba(15, 23, 42, 0.75)', borderRadius: '8px', border: '1px solid rgba(59, 130, 246, 0.2)', marginBottom: '1.5rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                    <span className="badge badge-primary">Phase 1 Case Study</span>
                    <h4 style={{ margin: 0, fontSize: '1.05rem', fontWeight: '700', color: '#93c5fd' }}>
                      {selectedAssessment.caseStudy.title || 'Case Study Scenario'}
                    </h4>
                  </div>
                  <div style={{ fontSize: '0.88rem', color: 'var(--text-secondary)', lineHeight: '1.65', whiteSpace: 'pre-wrap' }}>
                    {selectedAssessment.caseStudy.scenario}
                  </div>
                </div>
              )}

              <h4 style={{ fontSize: '1rem', fontWeight: '700', marginBottom: '1rem' }}>
                Phase 1 Predefined Questions & Answer Key ({selectedAssessment.caseStudyQuestions?.length || selectedAssessment.questions?.length || 0} MCQs)
              </h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                {(selectedAssessment.caseStudyQuestions?.length > 0 ? selectedAssessment.caseStudyQuestions : selectedAssessment.questions)?.map((q, idx) => (
                  <div key={idx} style={{ padding: '1rem', backgroundColor: 'rgba(15, 23, 42, 0.6)', borderRadius: '8px', border: '1px solid rgba(255, 255, 255, 0.06)' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                      <div style={{ fontWeight: '700', fontSize: '0.95rem' }}>
                        Q{idx + 1}. {q.questionText}
                      </div>
                      <span className="badge badge-info" style={{ fontSize: '0.7rem' }}>{q.skillName}</span>
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '6px', marginBottom: '8px' }}>
                      {q.options?.map((opt) => (
                        <div
                          key={opt.label}
                          style={{
                            padding: '6px 10px',
                            borderRadius: '6px',
                            fontSize: '0.85rem',
                            backgroundColor: opt.label === q.correctAnswer ? 'rgba(16, 185, 129, 0.15)' : 'rgba(255, 255, 255, 0.03)',
                            border: opt.label === q.correctAnswer ? '1px solid #10b981' : '1px solid rgba(255, 255, 255, 0.05)',
                            color: opt.label === q.correctAnswer ? '#10b981' : 'var(--text-primary)',
                            fontWeight: opt.label === q.correctAnswer ? '700' : 'normal',
                          }}
                        >
                          <strong>{opt.label}:</strong> {opt.text} {opt.label === q.correctAnswer && '✓ (Correct)'}
                        </div>
                      ))}
                    </div>

                    {q.explanation && (
                      <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', backgroundColor: 'rgba(255, 255, 255, 0.02)', padding: '6px', borderRadius: '4px' }}>
                        <strong>Explanation:</strong> {q.explanation}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>

            <div className="modal-footer">
              <button className="btn btn-secondary" onClick={() => setSelectedAssessment(null)}>Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
